// Top 100 Engineering Colleges in India
// IITs (23) + IIITs (25) + NITs (31) + Other Premier (21) = 100

export const TOP_COLLEGES = [
  // ── IITs (23) ──────────────────────────────────────────────────────────────
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Hyderabad",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Patna",
  "IIT Ropar",
  "IIT Bhubaneswar",
  "IIT Indore",
  "IIT Mandi",
  "IIT (ISM) Dhanbad",
  "IIT Varanasi (BHU)",
  "IIT Guwahati",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Jammu",
  "IIT Dharwad",
  "IIT Bhilai",
  "IIT Goa",

  // ── IIITs (25) ─────────────────────────────────────────────────────────────
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Allahabad",
  "IIIT Delhi",
  "IIIT Pune",
  "IIIT Gwalior",
  "IIIT Jabalpur",
  "IIIT Kancheepuram",
  "IIIT Kota",
  "IIIT Lucknow",
  "IIIT Manipur",
  "IIIT Nagpur",
  "IIIT Ranchi",
  "IIIT Srirangam (Trichy)",
  "IIIT Vadodara",
  "IIIT Kalyani",
  "IIIT Sri City",
  "IIIT Una",
  "IIIT Sonepat",
  "IIIT Bhopal",
  "IIIT Bhagalpur",
  "IIIT Agartala",
  "IIIT Raichur",
  "IIIT Dharwad",
  "IIIT Surat",

  // ── NITs (31) ──────────────────────────────────────────────────────────────
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal (NITK)",
  "NIT Calicut",
  "NIT Rourkela",
  "NIT Allahabad (MNNIT)",
  "NIT Jaipur (MNIT)",
  "NIT Nagpur (VNIT)",
  "NIT Bhopal (MANIT)",
  "NIT Durgapur",
  "NIT Silchar",
  "NIT Kurukshetra",
  "NIT Srinagar",
  "NIT Hamirpur",
  "NIT Jalandhar",
  "NIT Patna",
  "NIT Raipur",
  "NIT Agartala",
  "NIT Arunachal Pradesh",
  "NIT Delhi",
  "NIT Goa",
  "NIT Manipur",
  "NIT Meghalaya",
  "NIT Mizoram",
  "NIT Nagaland",
  "NIT Puducherry",
  "NIT Sikkim",
  "NIT Uttarakhand",
  "NIT Andhra Pradesh",
  "NIT Srinagar (J&K)",
  "NIT Tiruchirappalli",

  // ── Other Premier Institutions (21) ────────────────────────────────────────
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "VIT Vellore",
  "VIT Chennai",
  "Jadavpur University",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "NSIT Delhi",
  "PSG College of Technology",
  "Thapar Institute of Engineering & Technology",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "Amrita School of Engineering",
  "PEC University of Technology",
  "College of Engineering Pune (COEP)",
  "Institute of Chemical Technology (ICT Mumbai)",
  "Sardar Patel College of Engineering",
  "Veermata Jijabai Technological Institute (VJTI)",
  "Motilal Nehru National Institute of Technology",
  "Other",
] as const;

export type College = typeof TOP_COLLEGES[number];
